# Generated by Django 4.0.4 on 2022-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
